[package]
name = "tachyonic"
version = "0.0.1"
authors = ["Dustin Bensing <dustin.bensing@googlemail.com>"]

[dependencies]
orbclient = "0.2.11"
orbimage = "0.1.11"
nalgebra = "0.10.*"

#[profile.release]
#debug = true